; Listing generated by Microsoft (R) Optimizing Compiler Version 19.29.29917.0 

	TITLE	B:\003_¼ö¾÷»çÀü¼Ò½º¸ğÀ½\»çÀü¼Ò½º\»ï¼ºMODERNCPP\DAY10\3_thread7.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?a@@3HA						; a
PUBLIC	?b@@3HA						; b
_BSS	SEGMENT
?a@@3HA	DD	01H DUP (?)				; a
?b@@3HA	DD	01H DUP (?)				; b
_BSS	ENDS
PUBLIC	?foo@@YAXXZ					; foo
PUBLIC	?goo@@YAXXZ					; goo
PUBLIC	_main
; Function compile flags: /Ogtpy
; File B:\003_¼ö¾÷»çÀü¼Ò½º¸ğÀ½\»çÀü¼Ò½º\»ï¼ºMODERNCPP\DAY10\3_thread7.cpp
;	COMDAT _main
_TEXT	SEGMENT
_main	PROC						; COMDAT

; 27   : }

	xor	eax, eax
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File B:\003_¼ö¾÷»çÀü¼Ò½º¸ğÀ½\»çÀü¼Ò½º\»ï¼ºMODERNCPP\DAY10\3_thread7.cpp
;	COMDAT ?goo@@YAXXZ
_TEXT	SEGMENT
?goo@@YAXXZ PROC					; goo, COMDAT

; 19   : 	if (b == 1)
; 20   : 	{
; 21   : 		// aëŠ” ë°˜ë“œì‹œ 1ì¼ê¹Œìš” ?
; 22   : 	}
; 23   : }

	ret	0
?goo@@YAXXZ ENDP					; goo
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File B:\003_¼ö¾÷»çÀü¼Ò½º¸ğÀ½\»çÀü¼Ò½º\»ï¼ºMODERNCPP\DAY10\3_thread7.cpp
;	COMDAT ?foo@@YAXXZ
_TEXT	SEGMENT
?foo@@YAXXZ PROC					; foo, COMDAT

; 9    : 	a = b + 1;

	mov	eax, DWORD PTR ?b@@3HA			; b
	inc	eax
	mov	DWORD PTR ?a@@3HA, eax			; a

; 10   : 
; 11   : 
; 12   : 	__asm{ mfence }

	mfence

; 13   : 
; 14   : 	b = 1;

	mov	DWORD PTR ?b@@3HA, 1			; b

; 15   : }

	ret	0
?foo@@YAXXZ ENDP					; foo
_TEXT	ENDS
END
